-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) AS YEAR , MONTH(A.SALES_DATE) AS MONTH, B.GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO B, ONLINE_SALE A
WHERE B.USER_ID = A.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER